version: '3.7'
services:
  backend:
    build:
      context: .
    container_name: backend
    image: ildimas/bot_project:latest
    env_file:
      - .env
    depends_on:
      - db  
  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"