"""two objects

Revision ID: 2df23cd86fde
Revises: b7b2ee26d4f6
Create Date: 2024-09-05 17:29:30.959712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df23cd86fde'
down_revision: Union[str, None] = 'b7b2ee26d4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_additional_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('companies', sa.Column('company_hashed_password', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('company_corporeate_mail', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('company_phone', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('company_website', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('company_additional_info', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['company_corporeate_mail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'company_additional_info')
    op.drop_column('companies', 'company_website')
    op.drop_column('companies', 'company_phone')
    op.drop_column('companies', 'company_corporeate_mail')
    op.drop_column('companies', 'company_hashed_password')
    op.drop_table('users')
    # ### end Alembic commands ###
