"""user edit

Revision ID: 2fbd54f7b44f
Revises: aca4516b040f
Create Date: 2024-09-10 01:43:40.065003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbd54f7b44f'
down_revision: Union[str, None] = 'aca4516b040f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ticket_sf_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'tickets', ['ticket_sf_id'])
    op.drop_column('tickets', 'ticket_priority')
    op.add_column('users', sa.Column('user_sf_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['user_sf_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_sf_id')
    op.add_column('tickets', sa.Column('ticket_priority', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='unique')
    op.drop_column('tickets', 'ticket_sf_id')
    # ### end Alembic commands ###
