"""ticket obj

Revision ID: 543578e6c0c5
Revises: 2df23cd86fde
Create Date: 2024-09-06 20:49:03.622167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543578e6c0c5'
down_revision: Union[str, None] = '2df23cd86fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticket_name', sa.String(), nullable=False),
    sa.Column('ticket_priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('tickets')
    # ### end Alembic commands ###
