"""companies fix

Revision ID: d348c958dcd1
Revises: fc33080ceda4
Create Date: 2024-09-07 04:15:03.167090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd348c958dcd1'
down_revision: Union[str, None] = 'fc33080ceda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_company_corporeate_mail_key', 'companies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('companies_company_corporeate_mail_key', 'companies', ['company_corporeate_mail'])
    # ### end Alembic commands ###
